{% set version = "2.4.2" %}

package:
    name: solvespace
    version: {{ version }}

source:
    url: https://github.com/realthunder/solvespace/archive/v{{ version }}.tar.gz
    sha256: 0aee9bbb0fad109800e4d8f899fdd23c3d8c46019bb5ac57959023ae61f3fcc2

build:
    number: 0

requirements:
    build:
        - {{ compiler("cxx") }}
        - ninja
        - cmake
    host:
        - swig
        - python
        - libpng
        - zlib
        - fontconfig
        - json-c
        - libglu  # [linux]
    run:
        - python
test:
    imports:
        - _slvs

extra:
    recipe-maintainers:
        - looooo
