{% set version = "2.4.2" %}
{% set sha256 = "19d7162bab2ed4f554435b7441c2631389e644ee542e21d0dc5cb307eec4c05b" %}

package:
    name: solvespace
    version: {{ version }}

source:
    url: https://github.com/realthunder/solvespace/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
        - osx_python_linking.patch  # [osx]

build:
    number: 0

requirements:
    build:
        - {{ compiler("cxx") }}
        - ninja
        - cmake
    host:
        - swig
        - python
        - libpng
        - zlib
        - fontconfig
        - json-c
        - libglu  # [linux]
    run:
        - python
test:
    imports:
        - _slvs

extra:
    recipe-maintainers:
        - looooo
